name: dataprice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  crypto: ^3.0.3
  encrypt: ^5.0.3
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.0.0
  http: ^1.2.1
  http_interceptor: ^2.0.0
  shared_preferences: ^2.2.2
  go_router: ^14.0.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  mobile_scanner: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  custom_lint:
  riverpod_generator:
  riverpod_lint:

flutter:
  uses-material-design: true
